### ISSUE TITLE
Installation instructions are broken

### ISSUE THREAD

**Issue by corywright** [mitsuhiko/platter#26]
The [quickstart documentation](http://platter.pocoo.org/dev/quickstart/#installing-platter-packages) says to install platter using `pip`, however that is currently broken:

```
$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.

$ ./venv/bin/pip install platter
Downloading/unpacking platter
  Could not find any downloads that satisfy the requirement platter
Cleaning up...
No distributions at all found for platter
Storing debug log for failure in /Users/cwright/.pip/pip.log
```

The `pip.log` file:

```
Downloading/unpacking platter
  Getting page https://pypi.python.org/simple/platter/
  URLs to search for versions for platter:
  * https://pypi.python.org/simple/platter/
  Analyzing links from page https://pypi.python.org/simple/platter/
  Could not find any downloads that satisfy the requirement platter
Cleaning up...
  Removing temporary dir /Users/cwright/venv/build...
No distributions at all found for platter
Exception information:
Traceback (most recent call last):
  File "/Users/cwright/venv/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/cwright/venv/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/cwright/venv/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Users/cwright/venv/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for platter
```

**Comment by dan-passaro** [comment]
I'm guessing that's for when 1.0-legit-version comes out. Until then you can do `pip install "git+https://github.com/mitsuhiko/platter"`

**Comment by kottenator** [comment]
@mitsuhiko - how is it going with development? Any ETA for the first PyPI release? I don't mind if it'd be 0.5a1, not obligatory super-stable one ;) 

I really like the tool, it'd simplify my project deployment. But I cannot use Git link, I allowed to use only PyPI
